apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: roboticsready
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        # you can use any tiny image—here we’ll just echo every 5s
        image: busybox:1.35
        command: ["/bin/sh","-c"]
        args:
        - while true; do echo "👋 Hello from Flux on Azure Arc!" ; sleep 5; done
