apiVersion: v1
kind: Service
metadata:
  name: hello‑world
  namespace: roboticsready
spec:
  type: NodePort
  selector:
    app: hello‑world
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
