apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: roboticsready
spec:
  type: NodePort
  selector:
    app: helloworld
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
